[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.30.0"
wasm-bindgen-futures = "0.4.42"
web-sys = { version = "0.3", features = ["HtmlCanvasElement"] }
wasm-bindgen = "0.2"
